openai:
  api_key: "your_openai_api_key"
  api_url: "https://api.openai.com/v1/completions"
gemini:
  api_key: "your_gemini_api_key"
  api_url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent"
ollama:
  api_url: "http://localhost:11434/api/generate"
